### ISSUE TITLE
Breakage in a non-project

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#1084] opened 2018-11-28 23:41 UTC
Ok.... so recent changes have made it so that you absolutely CANNOT run anything that's not a "project".
This seems to be what completely screws it up:
https://github.com/ManiacalLabs/BiblioPixel/blob/ea9c256417b56d074b0e3bec2a046a983f2264a1/bibliopixel/project/project.py#L59

That is only set if it's running a project. Then you can see here that `push_to_driver()` is only called if top_level == True:
https://github.com/ManiacalLabs/BiblioPixel/blob/f65695daa44545ce462d16f3a4b720b0854962a0/bibliopixel/animation/animation.py#L159

This needs to be fixed ASAP. We aren't supposed to break support for old scripts.

**Comment by adammhaile** [comment] 2018-11-28 23:52
Broken in this commit: https://github.com/ManiacalLabs/BiblioPixel/commit/c5edfe31aeeef8d9a37734c730827eb5f9c24d80

**Comment by rec** [comment] 2018-11-29 13:29
Ah, wrong, it's in another script.  

And running that test works!

**Comment by rec** [comment] 2018-11-29 13:33
Ah, so the stated issue is not the actual issue

> That [`Animation.top_levelo`] is only set if it's running a project. 

This is not so:  https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/animation/animation.py#L9

Because of backwards compatibility, and because people aren't necessarily calling the parent construction, when I add a new variable these days, it's almost always added that way - setting it as a static member in the parent class which the derived child class can override.

And I can run the two main programs I have here (the one checked in and some old one I have lying around).

So :-/ I don't have a way to reproduce this issue.  Can you find me one?

**Comment by rec** [comment] 2018-11-29 13:35
Or even better - a stack trace!

**Comment by adammhaile** [comment] 2018-11-29 13:36
See #1083

**Comment by adammhaile** [comment] 2018-11-29 13:36
There is no stacktrace it doesn't bomb out, it just never updates the driver.

**Comment by rec** [comment] 2018-11-29 13:39
I saw #1083.  Isn't that obviously a windows thing?

From that trace:

> WARNING - load - This "path" entry does not exist: "G"

And you're using drive G: elsewhere.

I'm not sure there are tests for `path` using Windows directory prefixes.  

I had certainly not thought about them, and `:` might even hit a wrong pattern match (e.g. "thinks it's a URL" or "thinks it's YAML".


----

Can you reproduce it on something that isn't the serial port?

I did try all of this on the test board before I pushed the release!

**Comment by adammhaile** [comment] 2018-11-29 13:50
Why would that be a windows thing?
I manually debugged the code, including some outputs in key places and found that when I wasn't running with a project file that this line never gets called: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/animation/animation.py#L159
Run a .py script or all_pixel_test and it doesn't get run. Run a project file and it does, so the animation works.
Also, this was reported on a Raspberry Pi! https://github.com/ManiacalLabs/AllPixel/issues/10
Which I already attached to this issue.
As you'll see there I told him to go back to 3.4.30 and it worked as did it for me on Windows. This is most definitely not a windows issue.
Have you tried running this against an AllPixel? Even on Mac as fine.
I didn't actually try it on a Pi with SPI yet but I can tonight. Pretty sure it'll fail as well. Likely also with SimPixel.

**Comment by rec** [comment] 2018-11-29 13:58
(I was talking about 1083, not this bug, re: windows - only because the very first error was clearly a windows error and you seemed to miss it.)

Ah, es, it's likely I'm not able to detect whether an animation is top-level that way.  Unfortunately, simply deleting that, we go back to "every subanimation pushes on each frame".

I'll figure out some cleverer way to handle this.

Note that this regression was a consequence of the original issue, which was not projects-oriented.

**Comment by adammhaile** [comment] 2018-11-29 14:10
Yet it only is an issue when you don't run projects. I wasn't saying projects caused the failure just that it was how to reproduce it... don't use projects.
Anyways, glad we are on the same page.

**Closed** 2018-12-07 14:14 UTC
Labels: bug
