### ISSUE TITLE
`bibliopixel demo circle` doesn't seem to do anything.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#217] opened 2017-06-15 10:24 UTC
Other demos work fine.  Suspect it's that layout issue again...

**Comment by adammhaile** [comment] 2017-06-15 21:45
Circle works fine. The real problem is the fact that the pixels all show up really small. 
In order to make the circle layout actually look round, I have to lay out the pixels over a much larger area because SimPixel coordinates are INT only. So I basically scale by Pi so that all coords can wind up on integer values. The problem is this acts to make them all far apart and for the camera to zoom way out.

@mwcz Any thoughts for fixing this? Pixels default to size 5, but for circle I have to use ~20, and I added that slider to change them because of this issue. But the only fix I can see is to either have SimPixel auto resize the pixels or to find a way for SimPixel coords to be float.

**Comment by mwcz** [comment] 2017-06-16 13:57
@adammhaile Sure, the first solution I can think of is to give the initial particle size a linear relationship with camera distance.

Another option would be to remove the distance falloff from particle size entirely.  That's the default behavior of WebGL particles in fact, decreasing size with distance is [added behavior](https://github.com/ManiacalLabs/SimPixel/blob/201a10b7b0cec87e3e19f6b5e9350e64cc827aca/src/index.html#L50).  This option is sucky though because it would ruin the feeling of depth.

Possibly (?) the best option is to decide on an ideal scene size, then teach SimPixel to scale *every* scene down to that size.  Instead of pointing the particle position & color typed arrays at each new buffer from BiblioPixel directly, we'd need to check all values, decide on the scale factor, then apply the scale while copying the position values into a float32array.  It should still be crazy fast and would only happen on config messages, not every message.

**Comment by adammhaile** [comment] 2017-06-16 14:00
Interesting... I think the major problem with circle is that the particles
are always super far apart... so I *think* your "best option" helps solve
that? Certainly resolving to float values would be nice.

Question... any way to just let SimPixel config take float value
coordinates?

**Comment by adammhaile** [comment] 2017-06-20 22:57
@mwcz Any thoughts on the float?

**Comment by mwcz** [comment] 2017-06-21 13:39
@adammhaile Sorry, for some reason your first response didn't show me a github notification even though I'm subscribed to this issue.

Yeah, the "best" option would normalize the particle spread.  It would still accept ints from BP, and would scale the positions down to some ideal display size.

Sending floats should work just fine.  The one point that might conflict is floating point format, but that's so standard now that I bet it'll just work.  JavaScript's native numbers are weird 53-bit floats, BUT JavaScript's Float32Array and Float64Array are standard (IEEE Std 754-2008 according to the spec).

**Closed** 2017-06-22 01:51 UTC
Labels: bug

**Comment by adammhaile** [comment] 2017-06-22 02:01
Fixed in ManiacalLabs/SimPixel#3
